### ISSUE TITLE
Live crashes the plugin

### ISSUE THREAD

**Issue by cstackpole** [jaylinski/kodi-addon-vimeo#27]
Greetings,
With all the "fun news" going on in the world right now, I've had a lot more events/people begin live streaming over Vimeo. I've never used Vimeo much before, but I use Kodi near daily. When I found this plugin I was super ecstatic to watch on my big screen instead of my laptop. Works perfectly for all the pre-recorded videos that I've watched. Fails every time when I try to watch any live stream. This morning I asked a buddy who has a Vimeo premium account if he'd do some testing with me. Before he started a live stream, I could search for his account and watch any of his videos. As soon as he started a live stream it crashed, and it crashed every time I tried to look at his channel no matter how I did it. The moment he stopped his live stream, I could view his videos again.

According to Kodi, I've got the latest version of the plugin. I only have Raspberry Pi4's (4Gb memory versions) running Libreelec (latest version) to test Kodi on right now: LibreELEC (official): 9.2.1 (RPi4.arm)

The most informative error that I could find (also almost identical every time it crashes) is:
```
2020-03-29 09:46:07.908 T:2451551088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the follow
ing error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Could not convert JSON kind to model...
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vimeo/addon.py", line 3, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 95, in run
                                                search(handle, query)
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 144, in searc
h
                                                collection = listItems.from_collection(api.search(query, "videos"))
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 99, in
 search
                                                return self._map_json_to_collection(res)
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 218, i
n _map_json_to_collection
                                                raise RuntimeError("Could not convert JSON kind to model...")
                                            RuntimeError: Could not convert JSON kind to model...
                                            -->End of Python script error report<--
2020-03-29 09:46:07.971 T:2468336496   ERROR: GetDirectory - Error getting plugin://plugin.video.vimeo/<private link>
2020-03-29 09:46:07.983 T:3011697120   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vimeo/<private link>)
 failed
```
I didn't see anyone else reporting this problem. If you have another stream you want me to test on, please let me know. I can also try bumping up all the debugging options too if it helps.
Thanks!

**Comment by jaylinski** [comment]
Thanks for reporting the issue. I didn't even know Vimeo supported live streaming. I'll look into it. :+1:

**Comment by jaylinski** [comment]
@cstackpole I submitted the patch to the repository: https://github.com/xbmc/repo-plugins/pull/2795

This can take a while.

**Comment by cstackpole** [comment]
Whoa! I wasn't expecting a patch this fast. You are awesome. Thank you very much!
