### ISSUE TITLE
Error on saved search with non-ascii characters

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-addon-vimeo#34]
Searches with non-ascii characters will result in the following error:

```
2020-04-10 07:40:23.358 T:139727991629568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xfc' in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/addon.py", line 3, in <module>
                                                plugin.run()
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 40, in run
                                                args = urllib.parse.parse_qs(sys.argv[2][1:])
                                              File "/home/osboxes/.kodi/addons/script.module.future/libs/future/backports/urllib/parse.py", line 564, in parse_qs
                                                encoding=encoding, errors=errors)
                                              File "/home/osboxes/.kodi/addons/script.module.future/libs/future/backports/urllib/parse.py", line 616, in parse_qsl
                                                value = _coerce_result(value)
                                              File "/home/osboxes/.kodi/addons/script.module.future/libs/future/backports/urllib/parse.py", line 98, in _encode_result
                                                return obj.encode(encoding, errors)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--
```

Example search string: `Grün`

**Comment by jaylinski** [comment]
### Workaround

Re-enter your search query.

### Explanation

Python 2 apparently never could parse utf-8 encoded url components... (https://bugs.python.org/issue1712522)

This shouldn't be a problem, because we use the future library, but it has the same issue, since it encodes the content with `ascii`: https://github.com/PythonCharmers/python-future/blob/v0.17.0/src/future/backports/urllib/parse.py#L90

There is also this bug: https://github.com/PythonCharmers/python-future/issues/204

So the fix would be to write a custom url query parser (like the youtube addon does).
But I hate code complexity and fixing stuff for outdated software (Python 2), so I won't fix this issue.
I'll remove  python-future in Matrix, which will fix this issue in Kodi 19.
