### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by HrBeck** [jaylinski/kodi-addon-vimeo#46]
unfortunately I get a runtime error when trying to cast video from browser on windows-PC to kodi ("cast kodi"-addon for Firefox). The video is a vimeo one. you find examples under
[https://pur-life.de/artikel/seminare]
Thanks for any help.

`2021-01-17 16:25:59.055 T:1022358400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Api JSON seems to be invalid
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vimeo/addon.py", line 3, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 84, in run
                                                collection = listItems.from_collection(api.resolve_id(video_id))
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 139, in resolve_id
                                                return self._map_json_to_collection(res)
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 230, in _map_json_to_collection
                                                raise RuntimeError("Api JSON seems to be invalid")
                                            RuntimeError: Api JSON seems to be invalid
                                            -->End of Python script error report<--
2021-01-17 16:25:59.211 T:1937448976   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vimeo/play/?video_id=443194048]
`

**Comment by jaylinski** [comment]
@HrBeck This seems to be a protected video (can't be accessed via Vimeo: https://vimeo.com/443194048). I guess the owner has a pro account and only allows his own domain for embedding:

![Screenshot_2021-01-17 Settings - TypoAnimation](https://user-images.githubusercontent.com/1668766/104854112-4870e980-5905-11eb-98a5-b82f928ec54f.png)

That's why the Vimeo API returns an error.

**Comment by jaylinski** [comment]
A possible solution would be to use the "player"-API and a setting where you can add custom "protected" domains:

![Bildschirmfoto vom 2021-01-17 20-59-40](https://user-images.githubusercontent.com/1668766/104854454-13fe2d00-5907-11eb-9e04-c558b89d69c3.png)

**Comment by HrBeck** [comment]
Hello Jay,

 

thanks for having a look inside. 

Hmm… can I do anything on my side to follow your hint? Honestly I do not get your intention :)

Or is there anything I can request from the provider of the website to consider on changing their properties of their embedded videos?

Thank you!
Matthias

 

Von: Jay Linski [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Januar 2021 21:01
An: jaylinski/kodi-addon-vimeo <kodi-addon-vimeo@noreply.github.com>
Cc: HrBeck <el.patron@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jaylinski/kodi-addon-vimeo] RuntimeError (#46)

 

A possible solution would be to use the "player"-API and a setting where you can add custom "protected" domains:

 <https://user-images.githubusercontent.com/1668766/104854454-13fe2d00-5907-11eb-9e04-c558b89d69c3.png>

**Comment by jaylinski** [comment]
@HrBeck Nothing you can do (watching domain-protected videos just doesn't work right now). I know the cause of the problem and a possible workaround, but it's tricky to implement... so it could take a while until I find some time.

**Comment by 89z** [comment]
https://github.com/jaylinski/kodi-addon-vimeo/issues/67

**Comment by mm1992** [comment]
Hey,
wouldn't be possible to fix it in such a way the user has to provide domain referer which can be added as a header to the request? I've seen that this method works if I use browser or make a request with CURL.
However, I don't know how to fix another problem that in case of live streams link (probably with a token) expires after an hour even if the live is still on air - maybe you solved it (in non-encrypted livestreams).

**Comment by jaylinski** [comment]
@mm1992 Yes, that was the workaround I was thinking about.

Regarding the expiring tokens: I wasn't aware of that issue yet.

**Comment by mm1992** [comment]
The workaround - in a technical way - that I am thinking about (very probably same as yours) - goes as follows.
If a user runs the plugin like @HrBeck did in the first post - using that Kodi URL
- it could be like that: `plugin://plugin.video.vimeo/play/?video_id=443194048&referer=https://pur-life.de/`.
(this is the video from @HrBeck's post )
[Possibly, there would be a must to encode those slashes and another special characters near to "https".]
Next, in the source code, it would be possible to read that using: `referer = args.get("referer", [None])[0]`.
However, next it will be complicated, because you wrote your addon with a lot of functions and API from separate files. Each of those functions must be edited in order to attach "referer" value to their params. And I don't know how to do it in a clean way.
Also, I am not sure if there would be any situation when someone would attach referer just while navigating in an addon "by mouse". If yes, there could be maybe an option in context menu to attach referer?

**Comment by jaylinski** [comment]
@mm1992 For that to work, the software sending the request to Kodi (eg Cast to kodi browser extension) has to be updated to include the referrer.

I was thinking about displaying a text-input box to the user that prompts for the protected domain. This solution is not userfriendly at all, that's why I didn't add it until now.
