### ISSUE TITLE
Plugin fails to play videos with setting "Where can this be embedded? > Nowhere"

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-addon-vimeo#7]
```
2019-10-05 15:08:40.853 T:139863688980224   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'request'
                                            Traceback (most recent call last):
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/addon.py", line 3, in <module>
                                                plugin.run()
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 81, in run
                                                resolve_list_item(handle, collection[0][1])
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 128, in resolve_list_item
                                                resolved_url = api.resolve_media_url(list_item.getProperty("mediaUrl"))
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 68, in resolve_media_url
                                                return self._extract_url_from_video_config(res)
                                              File "/home/osboxes/.kodi/addons/plugin.video.vimeo/resources/lib/vimeo/api.py", line 166, in _extract_url_from_video_config
                                                video_files = video_config["request"]["files"]
                                            KeyError: 'request'
                                            -->End of Python script error report<--
2019-10-05 15:08:40.958 T:139865936590976   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vimeo/play/?video_id=364335684]
```

Source: https://forum.kodi.tv/showthread.php?tid=220437&pid=2890499#pid2890499

**Comment by jaylinski** [comment]
Some videos seem to be blocked by privacy settings.
```
{
   "message": "Because of its privacy settings, this video cannot be played here.",
   "title": "Sorry",
   "button": {
      "text": "Watch on Vimeo",
      "link": "https://vimeo.com/364335684"
   },
   "view": 7
}
```
(https://player.vimeo.com/video/364335684/config)

If it can't be circumvented, an informative error message should be displayed.

**Comment by jaylinski** [comment]
I tried to circumvent the block by setting a `Referer` header, which didn't work. I'll try to reverse engineer the Vimeo-App to see how they are getting the video.

**Comment by jaylinski** [comment]
I finally managed to find out how the Vimeo App is doing this. They are using an undocumented API endpoint. I'm still thinking about how to implement this.

Using the undocumented API will fix this issue, but it will also make the addon more unstable, since internal APIs tend to change more frequently... :thinking:
